//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThomasHarper_Cs_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoHubProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCategory { get; set; }
        public int ProductQuantity { get; set; }
        public decimal ProductCost { get; set; }
        public string ProductReplenishTime { get; set; }
    }
}
