//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThomasHarper_Cs_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CargoHubEntities : DbContext
    {
        public CargoHubEntities()
            : base("name=CargoHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CargoHubEmployeeTask> CargoHubEmployeeTasks { get; set; }
        public virtual DbSet<CargoHubProduct> CargoHubProducts { get; set; }
        public virtual DbSet<CargoHubUser> CargoHubUsers { get; set; }
    }
}
